server:
  port: 8083
spring:
  application:
    name: web-app
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
