spring.config.import: "optional:configserver:"

spring:
  application:
    name: web-app
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
# Optionnel : profil par défaut
# spring:
#   profiles:
#     active: default

